services:
  users:
    build: .
    container_name: micro-user
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db_user
  db_user:
    image: postgres
    container_name: db_user
    restart: always
    tty: true
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sge-micro-user